name: auto-renew

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt
      - run: playwright install chromium

      - run: python renew.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GT_URL: ${{ secrets.GT_URL }}
